### ISSUE TITLE
Upgrade for Pico 1.0.0 

### ISSUE THREAD

**Issue by theshka** [julindra/pico_post_share#1]
Would you consider upgrading this, and/or your other plugin(s) to be compatible with the newly-released `Pico 1.0.0-beta.1` and subsequent `Pico 1.0.0`? The plugin-upgrade docs are a work in progress, but can be viewed here: http://picocms.org/plugin-dev.html

Cheers! :smile:

**Comment by julindra** [comment]
Sure. I'll upgrade it later. Thanks
